# Generated by Django 4.1.13 on 2024-05-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('doctor_id', models.CharField(max_length=100)),
                ('appointment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_date', models.DateField()),
                ('diagnosis', models.CharField(max_length=255)),
                ('treatment', models.TextField()),
                ('notes', models.TextField()),
                ('medications', models.ManyToManyField(to='medical_records.medication')),
            ],
        ),
    ]
