# Generated by Django 4.1.13 on 2024-05-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='name',
            new_name='medication_id',
        ),
    ]
