# Generated by Django 4.1.13 on 2024-06-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_rename_name_medication_medication_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'verbose_name_plural': 'Medical Records'},
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='medication_id',
        ),
        migrations.AddField(
            model_name='medication',
            name='medical_record',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medical_records.medicalrecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatmentName', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('usage', models.TextField()),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='medical_records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyMH', models.TextField()),
                ('personalMH', models.TextField()),
                ('allergies', models.TextField()),
                ('immunizations', models.TextField()),
                ('medical_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical_records.medicalrecord')),
            ],
        ),
    ]
