# Generated by Django 4.1.13 on 2024-05-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fullName',
            new_name='name',
        ),
    ]
