# Generated by Django 4.1.13 on 2024-06-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_account_department_remove_doctor_specialization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='Department',
        ),
    ]
