# Generated by Django 4.1.13 on 2024-06-01 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_name_department_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.AddField(
            model_name='doctor',
            name='department_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='doctor.department'),
            preserve_default=False,
        ),
    ]
