# Generated by Django 4.1.13 on 2024-05-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='fullname',
        ),
    ]
