# Generated by Django 4.1.13 on 2024-05-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_name_doctor_fullname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='FullName',
        ),
    ]
